<?xml version="1.0"?>
<!DOCTYPE VARDEF [
<!ELEMENT VARDEF   ( TITLE | VAR | VARGROUP)+>
<!ATTLIST VARDEF   propfile CDATA #REQUIRED>
<!ELEMENT TITLE    (TITLE | VAR | VARGROUP)+>
<!ATTLIST TITLE    key CDATA #REQUIRED>
<!ELEMENT VAR      (#PCDATA)>
<!ELEMENT VARGROUP (#PCDATA)>
]>
<VARDEF propfile="system.hmi.text.pdptxt">
   <TITLE key="Group1">
      <VARGROUP>VG_Mold</VARGROUP>
      <VARGROUP>VG_Eject</VARGROUP>
      <VARGROUP>VG_Inject</VARGROUP>
      <VARGROUP>VG_Cores</VARGROUP>
      <VARGROUP>VG_Nozzle</VARGROUP>
      <VARGROUP>VG_Production</VARGROUP>
      <VARGROUP>VG_HeatingMold</VARGROUP>
      <VARGROUP>VG_HeatingNozzle</VARGROUP>
   </TITLE>
</VARDEF>
